name: Feature request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What do you want to see?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Why is this needed? What problem does it solve?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Other approaches you considered.
